name: Build Android APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build APK as root (auto-confirm prompts)
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/app \
            -w /app \
            kivy/buildozer:latest \
            android release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: bin/*.apk
