# .github/workflows/build-android.yml
name: Build Android APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-android:
    runs-on: ubuntu-latest
    env:
      ANDROID_API: "34"
      ANDROID_MINAPI: "21"
      NDK_VERSION: "25.2.9519653"
      BUILD_TOOLS_VERSION: "33.0.2"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y openjdk-17-jdk unzip wget zip build-essential zlib1g-dev libltdl-dev

      - name: Install pip dependencies including Buildozer & python-for-android
        run: |
          python3 -m pip install --upgrade pip setuptools wheel
          python3 -m pip install cython==0.29.36
          python3 -m pip install git+https://github.com/kivy/buildozer.git@master
          python3 -m pip install git+https://github.com/kivy/python-for-android.git@master

      - name: Prepare Android SDK/NDK
        run: |
          SDK_ROOT=.buildozer/android/platform/android-sdk
          mkdir -p $SDK_ROOT/cmdline-tools
          wget -q https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
          unzip -q cmdline-tools.zip -d cmdline-tools-temp
          mv cmdline-tools-temp/cmdline-tools $SDK_ROOT/cmdline-tools/latest
          rm -rf cmdline-tools.zip cmdline-tools-temp
          yes | $SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --sdk_root=$SDK_ROOT --licenses
          $SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --sdk_root=$SDK_ROOT "platform-tools" "platforms;android-${{ env.ANDROID_API }}" "build-tools;${{ env.BUILD_TOOLS_VERSION }}" "ndk;${{ env.NDK_VERSION }}"

      - name: Clone python-for-android recipes
        run: |
          mkdir -p .buildozer/android/platform
          cd .buildozer/android/platform
          git clone https://github.com/kivy/python-for-android.git

      - name: Build APK
        run: |
          export ANDROIDSDK=.buildozer/android/platform/android-sdk
          export ANDROID_HOME=$ANDROIDSDK
          export ANDROID_NDK_HOME=$ANDROIDSDK/ndk/${{ env.NDK_VERSION }}
          buildozer android clean
          buildozer android release

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: bin/*.apk
