name: Build Python APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  JAVA_HOME: /usr/lib/jvm/java-17-openjdk-amd64
  BUILD_TOOLS_VERSION: "33.0.2"
  ANDROID_PLATFORM: "android-33"
  NDK_VERSION: "25.2.9519653"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install apt dependencies
        run: |
          sudo apt update
          sudo apt install -y openjdk-17-jdk unzip wget zip build-essential zlib1g-dev

      - name: Setup Python tooling
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install --user cython buildozer==1.5.0 beautifulsoup4 requests
          echo "${HOME}/.local/bin" >> $GITHUB_PATH

      - name: Prepare Buildozer SDK directories
        run: |
          mkdir -p $HOME/.buildozer/android/platform/android-sdk/cmdline-tools
          mkdir -p $HOME/.buildozer/android/platform/android-sdk/build-tools
          mkdir -p $HOME/.buildozer/android/platform/android-sdk/platforms
          mkdir -p $HOME/.buildozer/android/platform/android-sdk/ndk
          mkdir -p $HOME/.buildozer/android/platform/android-sdk/platform-tools

      - name: Download & install Android commandline tools
        run: |
          cd $HOME
          TMP_ZIP=cmdline-tools.zip
          wget -q https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O $TMP_ZIP
          unzip -q $TMP_ZIP -d cmdline-tools-temp
          mkdir -p $HOME/.buildozer/android/platform/android-sdk/cmdline-tools/latest
          mv cmdline-tools-temp/cmdline-tools/* $HOME/.buildozer/android/platform/android-sdk/cmdline-tools/latest/
          rm -rf cmdline-tools-temp $TMP_ZIP

      - name: Export Buildozer Android paths
        run: |
          echo "$HOME/.buildozer/android/platform/android-sdk/cmdline-tools/latest/bin" >> $GITHUB_PATH
          echo "$HOME/.buildozer/android/platform/android-sdk/platform-tools" >> $GITHUB_PATH

      - name: Install SDK components inside Buildozer paths
        run: |
          SDK_ROOT=$HOME/.buildozer/android/platform/android-sdk
          yes | sdkmanager --sdk_root=$SDK_ROOT --licenses
          sdkmanager --sdk_root=$SDK_ROOT "platform-tools" "platforms;android-33" "build-tools;33.0.2" "ndk;25.2.9519653"

      - name: Build APK with Buildozer
        run: |
          export ANDROIDSDK=$HOME/.buildozer/android/platform/android-sdk
          export ANDROID_HOME=$ANDROIDSDK
          export ANDROID_NDK_HOME=$ANDROIDSDK/ndk/25.2.9519653
          export PATH=$HOME/.local/bin:$PATH
          buildozer android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: myapp-apk
          path: bin/*.apk
