name: Build Python APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  ANDROID_HOME: ${{ github.workspace }}/android-sdk
  ANDROID_SDK_ROOT: ${{ github.workspace }}/android-sdk
  JAVA_HOME: /usr/lib/jvm/java-17-openjdk-amd64
  BUILD_TOOLS_VERSION: "33.0.2"
  ANDROID_PLATFORM: "android-33"
  NDK_VERSION: "25.2.9519653"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install apt dependencies
        run: |
          sudo apt update
          sudo apt install -y openjdk-17-jdk unzip wget zip build-essential zlib1g-dev

      - name: Setup Python tooling
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install --user cython buildozer==1.5.0 beautifulsoup4 requests
          echo "${HOME}/.local/bin" >> $GITHUB_PATH

      - name: Create Android SDK directories
        run: mkdir -p "${ANDROID_SDK_ROOT}/cmdline-tools"

      - name: Download & setup Android commandline tools
        run: |
          cd $HOME
          TMP_ZIP=cmdline-tools.zip
          wget -q https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O $TMP_ZIP
          unzip -q $TMP_ZIP -d cmdline-tools-temp
          mkdir -p "${ANDROID_SDK_ROOT}/cmdline-tools/latest"
          mv cmdline-tools-temp/cmdline-tools/* "${ANDROID_SDK_ROOT}/cmdline-tools/latest/"
          rm -rf cmdline-tools-temp $TMP_ZIP

      - name: Export Android SDK paths
        run: |
          echo "${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin" >> $GITHUB_PATH
          echo "${ANDROID_SDK_ROOT}/platform-tools" >> $GITHUB_PATH

      - name: Accept licenses & install SDK components
        run: |
          yes | sdkmanager --sdk_root="${ANDROID_SDK_ROOT}" --licenses
          sdkmanager --sdk_root="${ANDROID_SDK_ROOT}" "platform-tools" "platforms;${ANDROID_PLATFORM}" "build-tools;${BUILD_TOOLS_VERSION}" "ndk;${NDK_VERSION}"

      - name: Build APK with Buildozer
        run: |
          export CFLAGS="-I${ANDROID_SDK_ROOT}/platforms/${ANDROID_PLATFORM}/arch-arm/usr/include:/usr/include"
          export LDFLAGS="-L${ANDROID_SDK_ROOT}/platforms/${ANDROID_PLATFORM}/arch-arm/usr/lib:/usr/lib"
          buildozer android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: myapp-apk
          path: bin/*.apk
