name: Build Collepedia Mobile APK

on:
  push:
    branches: [ main ] # Trigger on push to the main branch
  workflow_dispatch: # Allow manual triggering

jobs:
  build-android:
    runs-on: ubuntu-latest # Use the latest Ubuntu runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11' # Match the Python version you used

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          git \
          zip \
          unzip \
          build-essential \
          autoconf \
          libtool \
          pkg-config \
          zlib1g-dev \
          libncurses5-dev \
          libncursesw5-dev \
          cmake \
          libffi-dev \
          libssl-dev \
          openjdk-17-jdk # Required for Android SDK tools

    - name: Install Cython and Buildozer
      run: |
        pip install --upgrade pip
        pip install cython==0.29.36 # Specify a known compatible version
        pip install buildozer

    - name: Install app dependencies
      run: |
        pip install -r requirements.txt

    - name: Set up Android SDK
      uses: android-actions/setup-android@v3 # Use a dedicated action for SDK setup

    - name: Accept Android SDK Licenses
      run: yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses

    - name: Install Android Build Tools and Platform Tools
      run: |
        echo "Installing build-tools;33.0.2 and platform-tools..."
        $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "build-tools;33.0.2" "platform-tools" "platforms;android-31" # Install specific build-tools and platform for API 31

    - name: Build with Buildozer
      run: |
        # Set environment variables for Buildozer to find the SDK
        export ANDROID_HOME=$ANDROID_HOME
        export ANDROID_NDK_HOME=$ANDROID_NDK_HOME # Often set by setup-android action

        echo "ANDROID_HOME is $ANDROID_HOME"
        echo "ANDROID_NDK_HOME is $ANDROID_NDK_HOME"
        ls -la $ANDROID_HOME/build-tools # Verify build-tools exist
        
        buildozer android debug # Change to 'release' for a release build
        
    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: collepedia-mobile-apk
        path: bin/*.apk # Path where Buildozer places the APK
