name: Build Android APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prepare permissions
        run: |
          sudo chown -R $USER:$USER ${{ github.workspace }}

      - name: Build APK (non-root) using Buildozer
        run: |
          docker run --rm \
            -u $(id -u):$(id -g) \
            -v ${{ github.workspace }}:/home/user/app \
            -w /home/user/app \
            kivy/buildozer:latest \
            bash -c "yes | buildozer android debug"

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: bin/*.apk
